name: booking_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  cached_network_image: ^3.2.2
  equatable: ^2.0.5
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  sizer: ^2.0.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: null
  get_it: ^7.2.0
  image_picker: ^0.8.5+3
  google_maps_flutter: ^2.2.1

dev_dependencies:

  build_runner: null

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: null

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
